language: php
matrix:
  include:
    - php: 7.3

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=5.1
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction punktde/elastic-assetusageinnodes:dev-master
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/PunktDe.Elastic.AssetUsageInNodes
  - mv elastic-assetusageinnodes neos-base-distribution/Packages/Application/PunktDe.Elastic.AssetUsageInNodes
  - cd neos-base-distribution
script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/PunktDe.Elastic.AssetUsageInNodes/Tests/Functional
